apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ml-app
  namespace: ml-app-namespace
  labels:
    app: flask-ml-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-ml-app
  template:
    metadata:
      labels:
        app: flask-ml-app
    spec:
      containers:
        - name: flask-ml-container
          image: balesunilkumar/my-flask-ml-app:1.0
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
