apiVersion: v1
kind: Service
metadata:
  name: flask-ml-service
  namespace: ml-app-namespace
  labels:
    app: flask-ml-app
spec:
  selector:
    app: flask-ml-app
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 5000  # Port your Flask app listens on
  type: LoadBalancer
