apiVersion: v1
kind: Service
metadata:
  name: flask-ml-service
  namespace: ml-app-namespace
spec:
  selector:
    app: flask-ml-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer